spring:
  config:
    activate:
      on-profile: "dev"


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${DEV_DB_URL}
#    username: ${DEV_DB_USER}
#    password: ${DEV_DB_PASSWORD}
#  jwt:
#    refresh:
#      expiration: 604800 # 7일
#    access:
#      expiration: 86400 # 24시간
#    secret: ${JWT_SECRET_KEY}
#  security:
#    kakao:
#      client-id: ${KAKAO_REST_API_KEY}
#      redirect-uri: ${KAKAO_CALLBACK}

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG