spring:
  application:
    name: mom4u
  profiles:
    group:
      local: "local"
      dev: "dev"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true